language: python

python: "3.6"

sudo: required

before_script:
  - pip install chardet
  - git clone https://github.com/icwells/unixpath.git 
  - cd unixpath/ 
  - python setup.py install
  - cd ../

script: pytest
